[project]
name = "eval-m0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "gillharleencd..", email = "gillharleenkaur@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
]

[project.scripts]
eval-m0 = "eval_m0:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
